### ISSUE TITLE
Completely necessary Wabbabot improvement suggestion

### ISSUE THREAD

**Issue by Sederien** [wabbajack-tools/WabbaBot.NET#4]
Wabbabot should state, in the general channel, the following:

"Wabba!"

Once every 24-72 hours on a rand() timer. That is all.

---

Why? You brought this on yourself:
_Do you have any fun ideas? Feel free to suggest features (or report bugs) at https://github.com/wabbajack-tools/WabbaBot.NET/issues_

**Comment by tr4wzified** [comment]
Haha, got me cornered there :P
